### PR TITLE
Add some permalinks to bio

### PR DESCRIPTION
**Pull request by vzvenyach**
Even though you include specifics in your resume, I added some permanent URLs to your front-page bio to burnish your bona fides.

### CODE REVIEW

**Comment by konklone** [comment]
This is definitely merited, but I was planning to add links to specific initiatives in what is now the empty space below the description. I'll hold this open until I do that.

**Comment by konklone** [comment]
@vzvenyach I followed up on this - here's what I just added to my homepage. Thoughts?

screenshot from 2018-12-09 17-39-14

**Comment by vzvenyach** [comment]
Looks fabulous @konklone! 👍

**Comment by konklone** [comment]
:+1: Thank you!

**Pull request closed without merging**
